# Generated by Django 3.0.6 on 2020-05-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('c', 'czeka na akceptacje'), ('a', 'zaakceptowany'), ('n', 'niezaakceptowany')], max_length=1)),
                ('presentation', models.CharField(max_length=360)),
            ],
        ),
    ]
