# Generated by Django 3.0.6 on 2020-05-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecruitmentModel',
            new_name='Recruiter',
        ),
    ]
